api_platform:
    title: 'Stoke Drive API'
    description: 'Fournisseur de données Stoke Drive.'
    version: '1.0'
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/config/api_platform/resources']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        jsonapi: ['application/vnd.api+json']
        html: ['text/html']
        multipart: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']
    openapi:
        license:
            name: 'By Mehdi HAMIDI'
            url: 'https://github.com/HamidiMehdi'
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
