version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: access1234
      MINIO_ROOT_PASSWORD: access1234
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
