resources:
  App\Entity\User:
    attributes:
      normalization_context:
        groups: [ 'user:read' ]
      denormalization_context:
        groups: [ 'user:read' ]
    collectionOperations:
      get: ~
      post: ~
    itemOperations:
      get: ~
      put: ~
      patch: ~
      delete: ~
      me:
        method: GET
        path: /me
        controller: App\Controller\MeController
        read: false
        pagination_enabled: false