resources:
  App\Entity\User:
    attributes:
      normalization_context:
        groups: [ 'user:read' ]
      denormalization_context:
        groups: [ 'user:write' ]
    collectionOperations:
      post:
    itemOperations:
      get: ~
      me:
        method: GET
        path: /me
        controller: App\Controller\MeController
        read: false
        pagination_enabled: false