App\Entity\User:
  attributes:
    id:
      groups: [ 'user:read' ]
    firstname:
      groups: [ 'user:read', 'user:write' ]
    lastname:
      groups: [ 'user:read', 'user:write' ]
    email:
      groups: [ 'user:read', 'user:write' ]
    password:
      groups: [ 'user:write' ]
    userFrom:
      groups: [ 'user:read', 'user:write' ]
    createdAt:
      groups: [ 'user:read' ]
    updatedAt:
      groups: [ 'user:read' ]
    roles:
      groups: [ 'user:read' ]